sudo: required
install: true

env:
  global:
    - COMMIT=${TRAVIS_COMMIT::8}
    - REPO=browsersync/website

services:
  - docker

script:
  - docker build -f Dockerfile -t $REPO:$COMMIT .

after_success:
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - docker tag $REPO:$COMMIT $REPO:$TAG
  - docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
  - docker push $REPO
